/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.parser;

import portugol.node.*;
import portugol.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 0;
    }

    @Override
    public void caseTLineComment(@SuppressWarnings("unused") TLineComment node)
    {
        this.index = 1;
    }

    @Override
    public void caseTBlockCommnet(@SuppressWarnings("unused") TBlockCommnet node)
    {
        this.index = 2;
    }

    @Override
    public void caseTVector(@SuppressWarnings("unused") TVector node)
    {
        this.index = 3;
    }

    @Override
    public void caseTNInt(@SuppressWarnings("unused") TNInt node)
    {
        this.index = 4;
    }

    @Override
    public void caseTNReal(@SuppressWarnings("unused") TNReal node)
    {
        this.index = 5;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 6;
    }
}
