/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.analysis;

import java.util.*;
import portugol.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPHell().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAHell(AHell node)
    {
        defaultIn(node);
    }

    public void outAHell(AHell node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAHell(AHell node)
    {
        inAHell(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAHell(node);
    }
}
