/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.analysis;

import java.util.*;
import portugol.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        if(node.getDot() != null)
        {
            node.getDot().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComando());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PDeclaracao> copy = new ArrayList<PDeclaracao>(node.getDeclaracao());
            Collections.reverse(copy);
            for(PDeclaracao e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getBegin() != null)
        {
            node.getBegin().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        outAPrograma(node);
    }

    public void inAIdVar(AIdVar node)
    {
        defaultIn(node);
    }

    public void outAIdVar(AIdVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdVar(AIdVar node)
    {
        inAIdVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdVar(node);
    }

    public void inAIdArrayVar(AIdArrayVar node)
    {
        defaultIn(node);
    }

    public void outAIdArrayVar(AIdArrayVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdArrayVar(AIdArrayVar node)
    {
        inAIdArrayVar(node);
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdArrayVar(node);
    }

    public void inAStringValor(AStringValor node)
    {
        defaultIn(node);
    }

    public void outAStringValor(AStringValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        inAStringValor(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringValor(node);
    }

    public void inANIntValor(ANIntValor node)
    {
        defaultIn(node);
    }

    public void outANIntValor(ANIntValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANIntValor(ANIntValor node)
    {
        inANIntValor(node);
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        outANIntValor(node);
    }

    public void inANRealValor(ANRealValor node)
    {
        defaultIn(node);
    }

    public void outANRealValor(ANRealValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANRealValor(ANRealValor node)
    {
        inANRealValor(node);
        if(node.getNReal() != null)
        {
            node.getNReal().apply(this);
        }
        outANRealValor(node);
    }

    public void inARealTipo(ARealTipo node)
    {
        defaultIn(node);
    }

    public void outARealTipo(ARealTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTipo(ARealTipo node)
    {
        inARealTipo(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outARealTipo(node);
    }

    public void inAIntegerTipo(AIntegerTipo node)
    {
        defaultIn(node);
    }

    public void outAIntegerTipo(AIntegerTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerTipo(AIntegerTipo node)
    {
        inAIntegerTipo(node);
        if(node.getInteger() != null)
        {
            node.getInteger().apply(this);
        }
        outAIntegerTipo(node);
    }

    public void inACharTipo(ACharTipo node)
    {
        defaultIn(node);
    }

    public void outACharTipo(ACharTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACharTipo(ACharTipo node)
    {
        inACharTipo(node);
        if(node.getChar() != null)
        {
            node.getChar().apply(this);
        }
        outACharTipo(node);
    }

    public void inAVariableDeclaracao(AVariableDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAVariableDeclaracao(AVariableDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariableDeclaracao(AVariableDeclaracao node)
    {
        inAVariableDeclaracao(node);
        {
            List<PVarSemicolon> copy = new ArrayList<PVarSemicolon>(node.getVarSemicolon());
            Collections.reverse(copy);
            for(PVarSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAVariableDeclaracao(node);
    }

    public void inAConstDeclaracao(AConstDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConstDeclaracao(AConstDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstDeclaracao(AConstDeclaracao node)
    {
        inAConstDeclaracao(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getConst() != null)
        {
            node.getConst().apply(this);
        }
        outAConstDeclaracao(node);
    }

    public void inAVarSemicolon(AVarSemicolon node)
    {
        defaultIn(node);
    }

    public void outAVarSemicolon(AVarSemicolon node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarSemicolon(AVarSemicolon node)
    {
        inAVarSemicolon(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVarSemicolon(node);
    }

    public void inAAssignmentComando(AAssignmentComando node)
    {
        defaultIn(node);
    }

    public void outAAssignmentComando(AAssignmentComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignmentComando(AAssignmentComando node)
    {
        inAAssignmentComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getLArrow() != null)
        {
            node.getLArrow().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAAssignmentComando(node);
    }

    public void inAReadComando(AReadComando node)
    {
        defaultIn(node);
    }

    public void outAReadComando(AReadComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReadComando(AReadComando node)
    {
        inAReadComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        {
            List<PCommaVar> copy = new ArrayList<PCommaVar>(node.getCommaVar());
            Collections.reverse(copy);
            for(PCommaVar e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getRead() != null)
        {
            node.getRead().apply(this);
        }
        outAReadComando(node);
    }

    public void inAWriteComando(AWriteComando node)
    {
        defaultIn(node);
    }

    public void outAWriteComando(AWriteComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWriteComando(AWriteComando node)
    {
        inAWriteComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        {
            List<PCommaExp> copy = new ArrayList<PCommaExp>(node.getCommaExp());
            Collections.reverse(copy);
            for(PCommaExp e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWrite() != null)
        {
            node.getWrite().apply(this);
        }
        outAWriteComando(node);
    }

    public void inAIfComando(AIfComando node)
    {
        defaultIn(node);
    }

    public void outAIfComando(AIfComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfComando(AIfComando node)
    {
        inAIfComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getEndIf() != null)
        {
            node.getEndIf().apply(this);
        }
        {
            List<PElseStatement> copy = new ArrayList<PElseStatement>(node.getElseStatement());
            Collections.reverse(copy);
            for(PElseStatement e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getThen() != null)
        {
            node.getThen().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica1() != null)
        {
            node.getExpLogica1().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAIfComando(node);
    }

    public void inAEvaluateComando(AEvaluateComando node)
    {
        defaultIn(node);
    }

    public void outAEvaluateComando(AEvaluateComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEvaluateComando(AEvaluateComando node)
    {
        inAEvaluateComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getEndEvaluate() != null)
        {
            node.getEndEvaluate().apply(this);
        }
        {
            List<PElseEvaluate> copy = new ArrayList<PElseEvaluate>(node.getElseEvaluate());
            Collections.reverse(copy);
            for(PElseEvaluate e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PEvaluateBody> copy = new ArrayList<PEvaluateBody>(node.getEvaluateBody());
            Collections.reverse(copy);
            for(PEvaluateBody e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getEvaluate() != null)
        {
            node.getEvaluate().apply(this);
        }
        outAEvaluateComando(node);
    }

    public void inAWhileComando(AWhileComando node)
    {
        defaultIn(node);
    }

    public void outAWhileComando(AWhileComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileComando(AWhileComando node)
    {
        inAWhileComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getEndWhile() != null)
        {
            node.getEndWhile().apply(this);
        }
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica1() != null)
        {
            node.getExpLogica1().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        outAWhileComando(node);
    }

    public void inARepeatComando(ARepeatComando node)
    {
        defaultIn(node);
    }

    public void outARepeatComando(ARepeatComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARepeatComando(ARepeatComando node)
    {
        inARepeatComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica1() != null)
        {
            node.getExpLogica1().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getUntil() != null)
        {
            node.getUntil().apply(this);
        }
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRepeat() != null)
        {
            node.getRepeat().apply(this);
        }
        outARepeatComando(node);
    }

    public void inAForComando(AForComando node)
    {
        defaultIn(node);
    }

    public void outAForComando(AForComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForComando(AForComando node)
    {
        inAForComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getEndFor() != null)
        {
            node.getEndFor().apply(this);
        }
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        if(node.getUntil() != null)
        {
            node.getUntil().apply(this);
        }
        if(node.getBegin() != null)
        {
            node.getBegin().apply(this);
        }
        if(node.getOf() != null)
        {
            node.getOf().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getFor() != null)
        {
            node.getFor().apply(this);
        }
        outAForComando(node);
    }

    public void inAForStepComando(AForStepComando node)
    {
        defaultIn(node);
    }

    public void outAForStepComando(AForStepComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForStepComando(AForStepComando node)
    {
        inAForStepComando(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getEndFor() != null)
        {
            node.getEndFor().apply(this);
        }
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        if(node.getUntil() != null)
        {
            node.getUntil().apply(this);
        }
        if(node.getNSteps() != null)
        {
            node.getNSteps().apply(this);
        }
        if(node.getStep() != null)
        {
            node.getStep().apply(this);
        }
        if(node.getBegin() != null)
        {
            node.getBegin().apply(this);
        }
        if(node.getOf() != null)
        {
            node.getOf().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getFor() != null)
        {
            node.getFor().apply(this);
        }
        outAForStepComando(node);
    }

    public void inAElseStatement(AElseStatement node)
    {
        defaultIn(node);
    }

    public void outAElseStatement(AElseStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseStatement(AElseStatement node)
    {
        inAElseStatement(node);
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseStatement(node);
    }

    public void inAEvaluateBody(AEvaluateBody node)
    {
        defaultIn(node);
    }

    public void outAEvaluateBody(AEvaluateBody node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEvaluateBody(AEvaluateBody node)
    {
        inAEvaluateBody(node);
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        outAEvaluateBody(node);
    }

    public void inAElseEvaluate(AElseEvaluate node)
    {
        defaultIn(node);
    }

    public void outAElseEvaluate(AElseEvaluate node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseEvaluate(AElseEvaluate node)
    {
        inAElseEvaluate(node);
        {
            List<PComandoSemicolon> copy = new ArrayList<PComandoSemicolon>(node.getComandoSemicolon());
            Collections.reverse(copy);
            for(PComandoSemicolon e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColon() != null)
        {
            node.getColon().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseEvaluate(node);
    }

    public void inACommaVar(ACommaVar node)
    {
        defaultIn(node);
    }

    public void outACommaVar(ACommaVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACommaVar(ACommaVar node)
    {
        inACommaVar(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outACommaVar(node);
    }

    public void inACommaExp(ACommaExp node)
    {
        defaultIn(node);
    }

    public void outACommaExp(ACommaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACommaExp(ACommaExp node)
    {
        inACommaExp(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outACommaExp(node);
    }

    public void inAComandoSemicolon(AComandoSemicolon node)
    {
        defaultIn(node);
    }

    public void outAComandoSemicolon(AComandoSemicolon node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoSemicolon(AComandoSemicolon node)
    {
        inAComandoSemicolon(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAComandoSemicolon(node);
    }

    public void inAMinusExp1(AMinusExp1 node)
    {
        defaultIn(node);
    }

    public void outAMinusExp1(AMinusExp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExp1(AMinusExp1 node)
    {
        inAMinusExp1(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outAMinusExp1(node);
    }

    public void inAExp2Exp1(AExp2Exp1 node)
    {
        defaultIn(node);
    }

    public void outAExp2Exp1(AExp2Exp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp2Exp1(AExp2Exp1 node)
    {
        inAExp2Exp1(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        outAExp2Exp1(node);
    }

    public void inAExpLogica1Exp1(AExpLogica1Exp1 node)
    {
        defaultIn(node);
    }

    public void outAExpLogica1Exp1(AExpLogica1Exp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica1Exp1(AExpLogica1Exp1 node)
    {
        inAExpLogica1Exp1(node);
        if(node.getExpLogica1() != null)
        {
            node.getExpLogica1().apply(this);
        }
        outAExpLogica1Exp1(node);
    }

    public void inAExpComparacao(AExpComparacao node)
    {
        defaultIn(node);
    }

    public void outAExpComparacao(AExpComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpComparacao(AExpComparacao node)
    {
        inAExpComparacao(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getComparacao() != null)
        {
            node.getComparacao().apply(this);
        }
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        outAExpComparacao(node);
    }

    public void inASomaExp2(ASomaExp2 node)
    {
        defaultIn(node);
    }

    public void outASomaExp2(ASomaExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExp2(ASomaExp2 node)
    {
        inASomaExp2(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        if(node.getSoma() != null)
        {
            node.getSoma().apply(this);
        }
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outASomaExp2(node);
    }

    public void inAExp2Exp2(AExp2Exp2 node)
    {
        defaultIn(node);
    }

    public void outAExp2Exp2(AExp2Exp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp2Exp2(AExp2Exp2 node)
    {
        inAExp2Exp2(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outAExp2Exp2(node);
    }

    public void inAMaisSoma(AMaisSoma node)
    {
        defaultIn(node);
    }

    public void outAMaisSoma(AMaisSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisSoma(AMaisSoma node)
    {
        inAMaisSoma(node);
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        outAMaisSoma(node);
    }

    public void inAMenosSoma(AMenosSoma node)
    {
        defaultIn(node);
    }

    public void outAMenosSoma(AMenosSoma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosSoma(AMenosSoma node)
    {
        inAMenosSoma(node);
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outAMenosSoma(node);
    }

    public void inAOuLogica(AOuLogica node)
    {
        defaultIn(node);
    }

    public void outAOuLogica(AOuLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuLogica(AOuLogica node)
    {
        inAOuLogica(node);
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        outAOuLogica(node);
    }

    public void inAXorLogica(AXorLogica node)
    {
        defaultIn(node);
    }

    public void outAXorLogica(AXorLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAXorLogica(AXorLogica node)
    {
        inAXorLogica(node);
        if(node.getXor() != null)
        {
            node.getXor().apply(this);
        }
        outAXorLogica(node);
    }

    public void inAIgualComparacao(AIgualComparacao node)
    {
        defaultIn(node);
    }

    public void outAIgualComparacao(AIgualComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualComparacao(AIgualComparacao node)
    {
        inAIgualComparacao(node);
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        outAIgualComparacao(node);
    }

    public void inADiferenteComparacao(ADiferenteComparacao node)
    {
        defaultIn(node);
    }

    public void outADiferenteComparacao(ADiferenteComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADiferenteComparacao(ADiferenteComparacao node)
    {
        inADiferenteComparacao(node);
        if(node.getNotEqual() != null)
        {
            node.getNotEqual().apply(this);
        }
        outADiferenteComparacao(node);
    }

    public void inAMenorIgualComparacao(AMenorIgualComparacao node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualComparacao(AMenorIgualComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualComparacao(AMenorIgualComparacao node)
    {
        inAMenorIgualComparacao(node);
        if(node.getLEqual() != null)
        {
            node.getLEqual().apply(this);
        }
        outAMenorIgualComparacao(node);
    }

    public void inAMaiorIgualComparacao(AMaiorIgualComparacao node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualComparacao(AMaiorIgualComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualComparacao(AMaiorIgualComparacao node)
    {
        inAMaiorIgualComparacao(node);
        if(node.getGEqual() != null)
        {
            node.getGEqual().apply(this);
        }
        outAMaiorIgualComparacao(node);
    }

    public void inAMenorComparacao(AMenorComparacao node)
    {
        defaultIn(node);
    }

    public void outAMenorComparacao(AMenorComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorComparacao(AMenorComparacao node)
    {
        inAMenorComparacao(node);
        if(node.getLess() != null)
        {
            node.getLess().apply(this);
        }
        outAMenorComparacao(node);
    }

    public void inAMaiorComparacao(AMaiorComparacao node)
    {
        defaultIn(node);
    }

    public void outAMaiorComparacao(AMaiorComparacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorComparacao(AMaiorComparacao node)
    {
        inAMaiorComparacao(node);
        if(node.getGreater() != null)
        {
            node.getGreater().apply(this);
        }
        outAMaiorComparacao(node);
    }

    public void inAExp2Exp3(AExp2Exp3 node)
    {
        defaultIn(node);
    }

    public void outAExp2Exp3(AExp2Exp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp2Exp3(AExp2Exp3 node)
    {
        inAExp2Exp3(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        if(node.getMultDiv() != null)
        {
            node.getMultDiv().apply(this);
        }
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outAExp2Exp3(node);
    }

    public void inAExp3Exp3(AExp3Exp3 node)
    {
        defaultIn(node);
    }

    public void outAExp3Exp3(AExp3Exp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp3Exp3(AExp3Exp3 node)
    {
        inAExp3Exp3(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outAExp3Exp3(node);
    }

    public void inAMultMultDiv(AMultMultDiv node)
    {
        defaultIn(node);
    }

    public void outAMultMultDiv(AMultMultDiv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultMultDiv(AMultMultDiv node)
    {
        inAMultMultDiv(node);
        if(node.getStar() != null)
        {
            node.getStar().apply(this);
        }
        outAMultMultDiv(node);
    }

    public void inADivMultDiv(ADivMultDiv node)
    {
        defaultIn(node);
    }

    public void outADivMultDiv(ADivMultDiv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivMultDiv(ADivMultDiv node)
    {
        inADivMultDiv(node);
        if(node.getBar() != null)
        {
            node.getBar().apply(this);
        }
        outADivMultDiv(node);
    }

    public void inAParentesesExpExp4(AParentesesExpExp4 node)
    {
        defaultIn(node);
    }

    public void outAParentesesExpExp4(AParentesesExpExp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParentesesExpExp4(AParentesesExpExp4 node)
    {
        inAParentesesExpExp4(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAParentesesExpExp4(node);
    }

    public void inAExp5Exp4(AExp5Exp4 node)
    {
        defaultIn(node);
    }

    public void outAExp5Exp4(AExp5Exp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp5Exp4(AExp5Exp4 node)
    {
        inAExp5Exp4(node);
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outAExp5Exp4(node);
    }

    public void inAValorExp5(AValorExp5 node)
    {
        defaultIn(node);
    }

    public void outAValorExp5(AValorExp5 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValorExp5(AValorExp5 node)
    {
        inAValorExp5(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAValorExp5(node);
    }

    public void inAVarExp5(AVarExp5 node)
    {
        defaultIn(node);
    }

    public void outAVarExp5(AVarExp5 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarExp5(AVarExp5 node)
    {
        inAVarExp5(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVarExp5(node);
    }

    public void inAExpLogica2ExpLogica1(AExpLogica2ExpLogica1 node)
    {
        defaultIn(node);
    }

    public void outAExpLogica2ExpLogica1(AExpLogica2ExpLogica1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica2ExpLogica1(AExpLogica2ExpLogica1 node)
    {
        inAExpLogica2ExpLogica1(node);
        if(node.getExpLogica2() != null)
        {
            node.getExpLogica2().apply(this);
        }
        outAExpLogica2ExpLogica1(node);
    }

    public void inAOrExpLogica1(AOrExpLogica1 node)
    {
        defaultIn(node);
    }

    public void outAOrExpLogica1(AOrExpLogica1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExpLogica1(AOrExpLogica1 node)
    {
        inAOrExpLogica1(node);
        if(node.getExpLogica1() != null)
        {
            node.getExpLogica1().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getExpLogica2() != null)
        {
            node.getExpLogica2().apply(this);
        }
        outAOrExpLogica1(node);
    }

    public void inAXorExpLogica2(AXorExpLogica2 node)
    {
        defaultIn(node);
    }

    public void outAXorExpLogica2(AXorExpLogica2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAXorExpLogica2(AXorExpLogica2 node)
    {
        inAXorExpLogica2(node);
        if(node.getExpLogica2() != null)
        {
            node.getExpLogica2().apply(this);
        }
        if(node.getXor() != null)
        {
            node.getXor().apply(this);
        }
        if(node.getExpLogica3() != null)
        {
            node.getExpLogica3().apply(this);
        }
        outAXorExpLogica2(node);
    }

    public void inAExpLogica3ExpLogica2(AExpLogica3ExpLogica2 node)
    {
        defaultIn(node);
    }

    public void outAExpLogica3ExpLogica2(AExpLogica3ExpLogica2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica3ExpLogica2(AExpLogica3ExpLogica2 node)
    {
        inAExpLogica3ExpLogica2(node);
        if(node.getExpLogica3() != null)
        {
            node.getExpLogica3().apply(this);
        }
        outAExpLogica3ExpLogica2(node);
    }

    public void inAOrExpLogica3(AOrExpLogica3 node)
    {
        defaultIn(node);
    }

    public void outAOrExpLogica3(AOrExpLogica3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExpLogica3(AOrExpLogica3 node)
    {
        inAOrExpLogica3(node);
        if(node.getExpLogica3() != null)
        {
            node.getExpLogica3().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getExpLogica4() != null)
        {
            node.getExpLogica4().apply(this);
        }
        outAOrExpLogica3(node);
    }

    public void inAExpLogica3ExpLogica3(AExpLogica3ExpLogica3 node)
    {
        defaultIn(node);
    }

    public void outAExpLogica3ExpLogica3(AExpLogica3ExpLogica3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpLogica3ExpLogica3(AExpLogica3ExpLogica3 node)
    {
        inAExpLogica3ExpLogica3(node);
        if(node.getExpLogica4() != null)
        {
            node.getExpLogica4().apply(this);
        }
        outAExpLogica3ExpLogica3(node);
    }

    public void inANotExpLogica4(ANotExpLogica4 node)
    {
        defaultIn(node);
    }

    public void outANotExpLogica4(ANotExpLogica4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotExpLogica4(ANotExpLogica4 node)
    {
        inANotExpLogica4(node);
        if(node.getExpLogica4() != null)
        {
            node.getExpLogica4().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        outANotExpLogica4(node);
    }

    public void inAExp4ExpLogica4(AExp4ExpLogica4 node)
    {
        defaultIn(node);
    }

    public void outAExp4ExpLogica4(AExp4ExpLogica4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExp4ExpLogica4(AExp4ExpLogica4 node)
    {
        inAExp4ExpLogica4(node);
        if(node.getExpComparacao() != null)
        {
            node.getExpComparacao().apply(this);
        }
        outAExp4ExpLogica4(node);
    }
}
