/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ACommaExp extends PCommaExp
{
    private TComma _comma_;
    private POrExpression _orExpression_;

    public ACommaExp()
    {
        // Constructor
    }

    public ACommaExp(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") POrExpression _orExpression_)
    {
        // Constructor
        setComma(_comma_);

        setOrExpression(_orExpression_);

    }

    @Override
    public Object clone()
    {
        return new ACommaExp(
            cloneNode(this._comma_),
            cloneNode(this._orExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaExp(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public POrExpression getOrExpression()
    {
        return this._orExpression_;
    }

    public void setOrExpression(POrExpression node)
    {
        if(this._orExpression_ != null)
        {
            this._orExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._orExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._orExpression_ == child)
        {
            this._orExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._orExpression_ == oldChild)
        {
            setOrExpression((POrExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
