/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ADivMultDiv extends PMultDiv
{
    private TBar _bar_;

    public ADivMultDiv()
    {
        // Constructor
    }

    public ADivMultDiv(
        @SuppressWarnings("hiding") TBar _bar_)
    {
        // Constructor
        setBar(_bar_);

    }

    @Override
    public Object clone()
    {
        return new ADivMultDiv(
            cloneNode(this._bar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivMultDiv(this);
    }

    public TBar getBar()
    {
        return this._bar_;
    }

    public void setBar(TBar node)
    {
        if(this._bar_ != null)
        {
            this._bar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bar_ == child)
        {
            this._bar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bar_ == oldChild)
        {
            setBar((TBar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
