/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpComparacaoExp2 extends PExp2
{
    private PExpComparacao _expComparacao_;

    public AExpComparacaoExp2()
    {
        // Constructor
    }

    public AExpComparacaoExp2(
        @SuppressWarnings("hiding") PExpComparacao _expComparacao_)
    {
        // Constructor
        setExpComparacao(_expComparacao_);

    }

    @Override
    public Object clone()
    {
        return new AExpComparacaoExp2(
            cloneNode(this._expComparacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpComparacaoExp2(this);
    }

    public PExpComparacao getExpComparacao()
    {
        return this._expComparacao_;
    }

    public void setExpComparacao(PExpComparacao node)
    {
        if(this._expComparacao_ != null)
        {
            this._expComparacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expComparacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expComparacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expComparacao_ == child)
        {
            this._expComparacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expComparacao_ == oldChild)
        {
            setExpComparacao((PExpComparacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
