/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AFatorFator extends PFator
{
    private PFator _fator_;
    private PMult _mult_;
    private PElem _elem_;

    public AFatorFator()
    {
        // Constructor
    }

    public AFatorFator(
        @SuppressWarnings("hiding") PFator _fator_,
        @SuppressWarnings("hiding") PMult _mult_,
        @SuppressWarnings("hiding") PElem _elem_)
    {
        // Constructor
        setFator(_fator_);

        setMult(_mult_);

        setElem(_elem_);

    }

    @Override
    public Object clone()
    {
        return new AFatorFator(
            cloneNode(this._fator_),
            cloneNode(this._mult_),
            cloneNode(this._elem_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorFator(this);
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    public PMult getMult()
    {
        return this._mult_;
    }

    public void setMult(PMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PElem getElem()
    {
        return this._elem_;
    }

    public void setElem(PElem node)
    {
        if(this._elem_ != null)
        {
            this._elem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elem_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fator_)
            + toString(this._mult_)
            + toString(this._elem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._elem_ == child)
        {
            this._elem_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((PMult) newChild);
            return;
        }

        if(this._elem_ == oldChild)
        {
            setElem((PElem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
