/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVariableDeclaracao extends PDeclaracao
{
    private PTipo _tipo_;
    private TColon _colon_;
    private final LinkedList<PVarSemicolon> _varSemicolon_ = new LinkedList<PVarSemicolon>();

    public AVariableDeclaracao()
    {
        // Constructor
    }

    public AVariableDeclaracao(
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") List<?> _varSemicolon_)
    {
        // Constructor
        setTipo(_tipo_);

        setColon(_colon_);

        setVarSemicolon(_varSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AVariableDeclaracao(
            cloneNode(this._tipo_),
            cloneNode(this._colon_),
            cloneList(this._varSemicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableDeclaracao(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public LinkedList<PVarSemicolon> getVarSemicolon()
    {
        return this._varSemicolon_;
    }

    public void setVarSemicolon(List<?> list)
    {
        for(PVarSemicolon e : this._varSemicolon_)
        {
            e.parent(null);
        }
        this._varSemicolon_.clear();

        for(Object obj_e : list)
        {
            PVarSemicolon e = (PVarSemicolon) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._varSemicolon_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._colon_)
            + toString(this._varSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._varSemicolon_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        for(ListIterator<PVarSemicolon> i = this._varSemicolon_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVarSemicolon) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
