/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AXorExpLogica1 extends PExpLogica1
{
    private PExpLogica1 _expLogica1_;
    private TXor _xor_;
    private PExpLogica2 _expLogica2_;

    public AXorExpLogica1()
    {
        // Constructor
    }

    public AXorExpLogica1(
        @SuppressWarnings("hiding") PExpLogica1 _expLogica1_,
        @SuppressWarnings("hiding") TXor _xor_,
        @SuppressWarnings("hiding") PExpLogica2 _expLogica2_)
    {
        // Constructor
        setExpLogica1(_expLogica1_);

        setXor(_xor_);

        setExpLogica2(_expLogica2_);

    }

    @Override
    public Object clone()
    {
        return new AXorExpLogica1(
            cloneNode(this._expLogica1_),
            cloneNode(this._xor_),
            cloneNode(this._expLogica2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXorExpLogica1(this);
    }

    public PExpLogica1 getExpLogica1()
    {
        return this._expLogica1_;
    }

    public void setExpLogica1(PExpLogica1 node)
    {
        if(this._expLogica1_ != null)
        {
            this._expLogica1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica1_ = node;
    }

    public TXor getXor()
    {
        return this._xor_;
    }

    public void setXor(TXor node)
    {
        if(this._xor_ != null)
        {
            this._xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xor_ = node;
    }

    public PExpLogica2 getExpLogica2()
    {
        return this._expLogica2_;
    }

    public void setExpLogica2(PExpLogica2 node)
    {
        if(this._expLogica2_ != null)
        {
            this._expLogica2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica1_)
            + toString(this._xor_)
            + toString(this._expLogica2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica1_ == child)
        {
            this._expLogica1_ = null;
            return;
        }

        if(this._xor_ == child)
        {
            this._xor_ = null;
            return;
        }

        if(this._expLogica2_ == child)
        {
            this._expLogica2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica1_ == oldChild)
        {
            setExpLogica1((PExpLogica1) newChild);
            return;
        }

        if(this._xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(this._expLogica2_ == oldChild)
        {
            setExpLogica2((PExpLogica2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
