/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TEndEvaluate extends Token
{
    public TEndEvaluate()
    {
        super.setText("fim avalie");
    }

    public TEndEvaluate(int line, int pos)
    {
        super.setText("fim avalie");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndEvaluate(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndEvaluate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndEvaluate text.");
    }
}
