/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TEndFor extends Token
{
    public TEndFor()
    {
        super.setText("fim para");
    }

    public TEndFor(int line, int pos)
    {
        super.setText("fim para");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndFor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndFor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndFor text.");
    }
}
