/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TLineComment extends Token
{
    public TLineComment()
    {
        super.setText("//");
    }

    public TLineComment(int line, int pos)
    {
        super.setText("//");
        setLine(line);
        setPos(pos);
    }

    
    public Object clone()
    {
      return new TLineComment(getLine(), getPos());
    }

    
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLineComment(this);
    }

    
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLineComment text.");
    }
}
