/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class TStartBlockComment extends Token
{
    public TStartBlockComment()
    {
        super.setText("/*");
    }

    public TStartBlockComment(int line, int pos)
    {
        super.setText("/*");
        setLine(line);
        setPos(pos);
    }

    
    public Object clone()
    {
      return new TStartBlockComment(getLine(), getPos());
    }

    
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStartBlockComment(this);
    }

    
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStartBlockComment text.");
    }
}
